### ISSUE TITLE
`applyIndividualParameters` throws an error with V11

### ISSUE THREAD

**Issue by PavelBal** [esqLABS/esqlabsR#182]
```
Error in rClr::clrCall(task, "IsExplicitFormulaByPath", simulation$ref, : 
Type: OSPSuite.Utility.Exceptions.OSPSuiteException
Message: Could not find quantity with path 'Organism|Kidney|eGFR'.
Method: OSPSuite.Core.Domain.IQuantity singleQuantityByPath(OSPSuite.Core.Domain.IModelCoreSimulation, System.String)
Stack trace:
at OSPSuite.R.Services.ContainerTask.singleQuantityByPath(IModelCoreSimulation simulation, String path)
at OSPSuite.R.Services.ContainerTask.IsExplicitFormulaByPath(IModelCoreSimulation simulation, String path)
7.
rClr::clrCall(task, "IsExplicitFormulaByPath", simulation$ref, 
enc2utf8(path)) at utilities-individual.R#153
6.
condition(path) at utilities-parameters.R#195
5.
setParameterValuesByPathWithCondition(parameterPaths = allParamPaths, 
values = allParamValues, simulation = simulation, condition = condition) at utilities-individual.R#157
4.
applyIndividualParameters(individualCharacteristics, simulation) at utilities-simulation.R#55
3.
esqlabsR::initializeSimulation(simulation = simulation, individualCharacteristics = individualCharacteristics, 
additionalParams = params, simulateSteadyState = scenarioConfiguration$simulateSteadyState, 
steadyStateTime = scenarioConfiguration$steadyStateTime) at runScenarios.R#156
2.
initializeScenario(scenarioConfiguration = scenarioConfiguration, 
customParams = customParams) at runScenarios.R#18
1.
runScenarios(scenarioNames = scenarioNames, scenarioConfiguration = scenarioConfiguration, 
customParams = NULL, saveSimulationsToPKML = TRUE)
```

**Comment by PavelBal** [comment]
Depends on https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/807
